### PR TITLE
Fix `toValue(fn)` to not internaly call `fn` as a factory

### PR DESCRIPTION
**Pull request by hbroer**
Currently a function assigned via `toValue(fn)` results in `container.get(type)` executes it like a factory. This fixes the bug.

I also renamed some types to make it more readable than just `T` and `U`.

This needs more testing before merge I think.

Bug: #63 
Related closed MR and discussion: #64

New build size:
```
Build "@owja/ioc" to dist:
        917 B: ioc.js.gz
        780 B: ioc.js.br
        926 B: ioc.mjs.gz
        809 B: ioc.mjs.br
```

### CODE REVIEW

**Comment by hbroer** [comment]
@vic1707 hey dude, can you check this out at your project to see if the fix and my other changes do not break your work?

**Comment by hbroer** [comment]
I published a new alpha (2.0.0-alpha.7)

**Review by vic1707 — APPROVED** [review]
LGTM, the tests pass, so we're good. 
I was only using `toValue` with finite values so it won't impact me.
BTW thank you for all the renaming!
P.S: if possible, think about renaming in different commits to simplify the review process (I had a hard time figuring out what was the main change) 😉

**Comment by hbroer** [comment]
sorry about the big commit. I was a bit in trance haha ;-)

**Pull request merged**
